on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: bishalcontainer1acr.azurecr.io
        username: ${{secrets.acr_bishalcontainer1acr_username}}
        password: ${{secrets.acr_bishalcontainer1acr_password}}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t bishalcontainer1acr.azurecr.io/bishalbugbashaksbf80:${{github.sha}}
        docker push bishalcontainer1acr.azurecr.io/bishalbugbashaksbf80:${{github.sha}}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{secrets.aks_bishalbugbashaks_kubeConfig}}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep bishalbugbashaksc5e2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace bishalbugbashaksc5e2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: bishalbugbashaksc5e2
        container-registry-url: bishalcontainer1acr.azurecr.io
        container-registry-username: ${{secrets.acr_bishalcontainer1acr_username}}
        container-registry-password: ${{secrets.acr_bishalcontainer1acr_password}}
        secret-name: bishalbugbasdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: bishalbugbashaksc5e2
        manifests: |
          manifests/deployment-d7dd.yml
          manifests/service-d7dd.yml
          manifests/ingress-d7dd.yml
        images: |
          bishalcontainer1acr.azurecr.io/bishalbugbashaksbf80:${{github.sha}}
        imagepullsecrets: |
          bishalbugbasdockerauth